# Generated by Django 2.1.1 on 2020-04-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20200427_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_per_unit',
            field=models.IntegerField(blank=True, help_text='quantity that items are shipped per unit. Ex. 1Ltr per bottle of oil', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(blank=True, help_text='Price per unit of product. Ex. Price of 1Ltr oil per bottle', null=True),
        ),
    ]
