# Generated by Django 2.1.1 on 2020-05-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20160107_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='pricing_strategy',
            field=models.CharField(blank=True, choices=[('PREMIUM', 'Premium'), ('GOLD', 'Gold'), ('', 'None')], default='', help_text='Specify Premium or Gold for child products. Not nessasary for Parent', max_length=100),
        ),
    ]
