# Generated by Django 2.1.1 on 2020-05-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20170821_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, default='', help_text='Specify tag for child product only. Ex. Certified Organic', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, help_text='Total weight of this Product Purchase', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('kilogram', 'Kg'), ('litre', 'Ltr'), ('millilitre', 'ML')], default='', help_text='Unit used to measure Weight. Ex. Kilogram used to measure quanitity of Pulses. Optional for child product. For parent specify it.', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_options',
            field=models.ManyToManyField(blank=True, help_text="Options are values that can be associated with a item when it is added to a customer's basket.  This could be something like a personalised message to be printed on a T-shirt.", to='catalogue.Option', verbose_name='Product options'),
        ),
    ]
