# Generated by Django 2.1.1 on 2020-05-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20170821_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is it ready to sale or not ?.'),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_strategy',
            field=models.CharField(blank=True, choices=[('PREMIUM', 'Premium'), ('GOLD', 'Gold'), ('', 'None')], default='', help_text='Specify Premium or Gold for child products. Not nessasary for Parent', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_per_unit',
            field=models.IntegerField(blank=True, help_text='quantity that items are shipped per unit. Ex. 1Ltr per bottle of oil', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_unit',
            field=models.CharField(choices=[('kilogram', 'Kg'), ('litre', 'Ltr'), ('millilitre', 'ML')], default='', help_text='Unit used to measure Quantity. Ex. Kilogram used to measure quanitity of Pulses. Optional for child product. For parent specify it.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, default='', help_text='Specify tag for child product only. Ex. Certified Organic', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.FloatField(blank=True, help_text='Total price of this Product Purchase', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(blank=True, help_text='Total weight of this Product Purchase', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(blank=True, help_text='Price per unit of product. Ex. Price of 1Ltr oil per bottle', null=True),
        ),
    ]
