# Generated by Django 2.1.1 on 2020-04-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_product_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is it ready to sale or not ?.'),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_strategy',
            field=models.CharField(choices=[('PREMIUM', 'Premium'), ('GOLD', 'Gold')], default='', help_text='Specify Premium or Gold for child products. Not nessasary for Parent', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_per_unit',
            field=models.IntegerField(blank=True, default=None, help_text='quantity that items are shipped per unit. Ex. 1Ltr per bottle of oil'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_unit',
            field=models.CharField(choices=[('kilogram', 'Kg'), ('litre', 'Ltr')], default='', help_text='Unit used to measure Quantity. Ex. Kilogram used to measure quanitity of Pulses. Optional for child product. For parent specify it.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(default='', help_text='Specify tag for child product only. Ex. Certified Organic', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.FloatField(help_text='Total price of this Product Purchase', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(help_text='Total weight of this Product Purchase', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(blank=True, default=None, help_text='Price per unit of product. Ex. Price of 1Ltr oil per bottle'),
        ),
    ]
