# Generated by Django 2.1.1 on 2020-05-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_product_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
    ]
