# Generated by Django 2.1.1 on 2020-05-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20200506_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_quantity',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_per_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('kilogram', 'Kg'), ('litre', 'Ltr'), ('millilitre', 'ML')], default='', help_text='Unit used to measure Weight. Ex. Kilogram used to measure quanitity of Pulses. Optional for child product. For parent specify it.', max_length=20),
        ),
    ]
