# Generated by Django 2.1.1 on 2020-04-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20200427_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pricing_strategy',
            field=models.CharField(choices=[('PREMIUM', 'Premium'), ('GOLD', 'Gold'), ('', 'None')], default='', help_text='Specify Premium or Gold for child products. Not nessasary for Parent', max_length=100),
        ),
    ]
