# Generated by Django 2.1.1 on 2020-05-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20200509_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pricing_strategy',
        ),
    ]
