# Generated by Django 2.1.1 on 2020-04-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20200427_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pricing_strategy',
            field=models.CharField(blank=True, choices=[('PREMIUM', 'Premium'), ('GOLD', 'Gold'), ('', 'None')], default='', help_text='Specify Premium or Gold for child products. Not nessasary for Parent', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, default='', help_text='Specify tag for child product only. Ex. Certified Organic', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_price',
            field=models.FloatField(blank=True, help_text='Total price of this Product Purchase', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(blank=True, help_text='Total weight of this Product Purchase', null=True),
        ),
    ]
