# Generated by Django 2.1.1 on 2020-04-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20200427_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_unit',
            field=models.CharField(choices=[('kilogram', 'Kg'), ('litre', 'Ltr'), ('millilitre', 'ML')], default='', help_text='Unit used to measure Quantity. Ex. Kilogram used to measure quanitity of Pulses. Optional for child product. For parent specify it.', max_length=20),
        ),
    ]
