# Generated by Django 2.1.1 on 2020-05-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_conditionaloffer_exclusive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='type',
            field=models.CharField(blank=True, choices=[('Percentage', "Discount is a percentage off of the product's value"), ('Absolute', "Discount is a fixed amount off of the product's value"), ('Fixed per product', "Discount is a fixed amount off of each product's value that match condition"), ('Multibuy', 'Discount is to give the cheapest product for free'), ('Fixed price', 'Get the products that meet the condition for a fixed price'), ('Shipping absolute', 'Discount is a fixed amount of the shipping cost'), ('Shipping fixed price', 'Get shipping for a fixed price'), ('Shipping percentage', 'Discount is a percentage off of the shipping cost')], max_length=128, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='conditionaloffer',
            name='max_user_applications',
            field=models.PositiveIntegerField(blank=True, help_text='The number of times a single user can use this offer', null=True, verbose_name='Max user applications'),
        ),
        migrations.AlterField(
            model_name='conditionaloffer',
            name='name',
            field=models.CharField(help_text="This is displayed within the customer's basket", max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='conditionaloffer',
            name='offer_type',
            field=models.CharField(choices=[('Site', 'Site offer - available to all users'), ('Flash Sale', 'Flash Sale offer - short-term discount for the specific product'), ('Voucher', 'Voucher offer - only available after entering the appropriate voucher code'), ('User', 'User offer - available to certain types of customer_final'), ('Session', 'Session offer - temporary offer, available for a customer_final for the duration of their session')], default='Site', max_length=128, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='range',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Public ranges have a customer-facing page', verbose_name='Is public?'),
        ),
    ]
